service: tutorial-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  app:
    handler: server.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline